<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [18 24 30 36 42]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [0]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
def matrix_mul(A, B):
    # write your cod
   R=[[0 for i in range(c2)] for j in range(r1)] 
   for i in range(r1):
      for j in range(c2):
         for k in range(c1):
            R[i][j]+=A[i][k]*B[k][j]

   print("Product of Matrices A and B: ")
   for i in range(r1):
      for j in range(c2):
         print(R[i][j],end=" ")
      print()


r1=int(input("input no of row1 = "))
c1=int(input("input no of col1 = "))
A=[[0 for i in range(c1)] for j in range(r1)] 
print("Enter Matrix value of A:")
for i in range(r1):
    for j in range(c1):
       A[i][j]=int(input("A[{}][{}] ".format(i,j)))


r2=int(input("input no of row2 = "))
c2=int(input("input no of col2 = "))
B=[[0 for i in range(c2)] for j in range(r2)] 
print("Enter Matrix value of B:")
for i in range(r2):
    for j in range(c2):
       B[i][j]=int(input("B[{}][{}] ".format(i,j)))


if(c1==r2):
   matrix_mul(A, B)
else:
   print("multiplication not possible")


input no of row1 =  2
input no of col1 =  2


Enter Matrix value of A:


A[0][0]  1
A[0][1]  2
A[1][0]  3
A[1][1]  4
input no of row2 =  2
input no of col2 =  5


Enter Matrix value of B:


B[0][0]  1
B[0][1]  2
B[0][2]  3
B[0][3]  4
B[0][4]  5
B[1][0]  5
B[1][1]  6
B[1][2]  7
B[1][3]  8
B[1][4]  9


Product of Matrices A and B: 
11 14 17 20 23 
23 30 37 44 51 


<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [0]:
from random import uniform
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
import random
from functools import reduce
import pdb

def pick_a_number_from_list(A):
    cum_sum=0
    cum_sum=[sum(A[:x+1]) for x in range(len(A))]
    sum1=reduce(lambda x, y : x+y, A)
    # pdb.set_trace()
    rand = int(random.uniform(0,sum1))
    number=0
    for i in range(len(cum_sum)):
        if(rand>=cum_sum[i] and rand<cum_sum[i+1]):
            return A[i+1]
    # pdb.set_trace()
    return number

def sampling_based_on_magnitued():
   A=[]
   n=int(input("enter the n: \n"))
   for i in range(0,n):
      ele=int(input("enter element {}\n".format(i)))
      A.append(ele)
    #A = [0,5,27,6,13,28,100,45,10,79]
   res = dict()
   for i in range(1,100):
      number = pick_a_number_from_list(A)
      if number not in res:
         res[number] = 1
      else:
         res[number]+=1
   print(res)
# pdb.set_trace()
sampling_based_on_magnitued()

enter the n: 
 10
enter element 0
 0
enter element 1
 5
enter element 2
 27
enter element 3
 6
enter element 4
 13
enter element 5
 28
enter element 6
 100
enter element 7
 45
enter element 8
 10
enter element 9
 79


{100: 35, 79: 23, 10: 4, 27: 14, 13: 3, 28: 8, 6: 4, 45: 8}


<h3> Q3: Replace the digits in the string with #</h3>

Consider a string that will have digits in that, we need to remove all the characters which are not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [0]:
import re
import string
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

txt = input("enter string")
print('#'* len(re.sub('\D', '', txt)))
hash=''.join('#' for c in txt if c.isdigit())
if '#' not in hash:
   print("empty")

enter string #2a$#b%c%561#


####


<h3> Q4: Students marks dashboard</h3>

Consider the marks list of class students given in two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on. <br><br>

Your task is to print the name of students

<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks.</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]

a. 
student8  98
student10 80
student2  78
student5  48
student7  47

b.
student3 12
student4 14
student9 35
student6 43
student1 45

c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [0]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
marks = [45, 78,12, 14, 48, 43, 47, 98, 35, 80]
temp=marks.copy()
finalList1=[]
finalList2=[]
finalList3=[]
print("\n ======= Top Five Marks ======== \n")
for i in range(0,5):
   max=0
   for j in range(len(temp)):
      if temp[j]>max:
         max=temp[j]
   temp.remove(max)
   finalList1.append(max)
for k in finalList1:
   print(students[marks.index(k)], k)

print("\n ========= Least Five Marks ======== \n")
for i in range(0,5):
   min=9999
   for j in range(len(temp)):
      if temp[j]<min:
         min=temp[j]
   temp.remove(min)
   finalList2.append(min)
for k in finalList2:
   print(students[marks.index(k)], k)

print("\n ========== Precentile ========== \n")
import math
per_25 = math.ceil((25 / 100) * int(len(marks)))
per_75 = math.ceil((75 / 100) * int(len(marks)))

sorted_marks=sorted(marks)
finalList3 = [i for i in marks if i >= sorted_marks[per_25-1] and i < sorted_marks[per_75-1]]
for k in sorted(finalList3):
   print(students[marks.index(k)], k)


 ======= Top Five Marks ======== 

student8 98
student10 80
student2 78
student5 48
student7 47

 ========= Least Five Marks ======== 

student3 12
student4 14
student9 35
student6 43
student1 45

 ========== Precentile ========== 

student9 35
student6 43
student1 45
student7 47
student5 48


<h3> Q5: Find the closest points</h3>

Consider you are given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P

<br>Cosine distance between two points (x,y) and (p,q) is defined as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [0]:
import math

# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can free to change all these codes/structure

mylist=[]
mylist1=[]
num=int(input("enter the n:"))
for i in range(0,num):
   x=int(input("enter x \n"))
   y=int(input("enter y \n"))
   mylist.append(x)
   mylist1.append(y)
P=(3,-4)
S=[(mylist,mylist1) for (mylist1,mylist) in zip(mylist1,mylist)]
print(S)
S.sort(key=lambda x: math.sqrt((float(x[0]) - P[0]) ** 2 +(float(x[1]) - (P[1])) ** 2))
print(S[:5])

enter the n: 9
enter x 
 1
enter y 
 2
enter x 
 3
enter y 
 4
enter x 
 -1
enter y 
 1
enter x 
 6
enter y 
 -7
enter x 
 0
enter y 
 6
enter x 
 -5
enter y 
 -8
enter x 
 -1
enter y 
 -1
enter x 
 6
enter y 
 0
enter x 
 1
enter y 
 -1


[(1, 2), (3, 4), (-1, 1), (6, -7), (0, 6), (-5, -8), (-1, -1), (6, 0), (1, -1)]
[(1, -1), (6, -7), (-1, -1), (6, 0), (1, 2)]


<h3> Q6: Find which line separates oranges and apples</h3>

Consider you are given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string format, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: You need to do string parsing here and get the coefficients of x,y and intercept.
</pre>
Your task here is to print "YES"/"NO" for each line given. You should print YES, if all the red points are one side of the line and blue points are on other side of the line, otherwise you should print NO.
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [0]:
import math
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings
import re
# Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
# Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
mylist=[]
mylist1=[]
num=int(input("enter the n:"))
for i in range(0,num):
   x=int(input("enter x for Red\n"))
   y=int(input("enter y for Red\n"))
   mylist.append(x)
   mylist1.append(y)
Red=[(mylist,mylist1) for (mylist1,mylist) in zip(mylist1,mylist)]
mylist.clear()
mylist1.clear()
for i in range(0,num):
   x=int(input("enter x for Blue\n"))
   y=int(input("enter y for Blue \n"))
   mylist.append(x)
   mylist1.append(y)
Blue=[(mylist,mylist1) for (mylist1,mylist) in zip(mylist1,mylist)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3"]
count=0
count1=0
for i in Lines:
   z = re.findall(r'[\d\.\-\+]+', i)
   r=[float(s) for s in re.findall('[\d\.\d]+',i)]
   for j in range(len(r)):
#       print(r[i])
      z[j]=float(z[j])
      sq=math.sqrt((r[0]*r[0])+(r[1]*r[1]))
      sq=round(dn,1)
#       print(dn)
   for k in range(len(Red)):
      for l in range(0,2):
         nn=(z[0]*Red[k][0]+z[1]*Red[k][1]+z[2])
         a=nn/sq
         if(a>0):
            count=count+1
         else:
            count=count-1
   for m in range(len(Blue)):
      for n in range(0,2):
         nn1=(z[0]*Blue[m][0]+z[1]*Blue[m][1]+z[2])
         a1=nn1/sq
         if(a1>0):
            count1=count1+1
         else:
            count1=count1-1
   if(abs(count1)==count):
      print("Yes")
   else:
      print("No")

enter the n: 3
enter x for Red
 2
enter y for Red
 3
enter x for Red
 4
enter y for Red
 2
enter x for Red
 5
enter y for Red
 6
enter x for Blue
 7
enter y for Blue 
 5
enter x for Blue
 7
enter y for Blue 
 6
enter x for Blue
 8
enter y for Blue 
 4


Yes
No
No


<h3> Q7: Filling the missing values in the specified format</h3>

You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 

<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [0]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings
def job(x, a, b):
    if a == -1:
        v = float(x[b])/(b+1)
        for i in range(a+1,b+1):
            x[i] = v
    elif b == -1:
        v = float(x[a])/(len(x)-a)
        for i in range(a, len(x)):
            x[i] = v
    else:
        v = (float(x[a])+float(x[b]))/(b-a+1)
        for i in range(a,b+1):
            x[i] = v
    return x
def curve_smoothing(text):
    x = text.replace(" ","").split(",")
    y = [i for i, v in enumerate(x) if v != '_']
    if y[0] != 0:
        y = [-1] + y
    if y[-1] != len(x)-1:
        y = y + [-1]    
    for (a, b) in zip(y[:-1], y[1:]): 
        job(x,a,b)          
    return x
str=input("input string")
a=curve_smoothing(str)
print(a)

input string _,_,30,_,_,_,50,_,_


[10.0, 10.0, 12.0, 12.0, 12.0, 12.0, 4.0, 4.0, 4.0]


<h3> Q8: Find the probabilities</h3>

You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. The first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. The second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>



In [0]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings
allRow = []
SecondColoumn = []
def compute_conditional_probabilites(A):
   for i in range(len(A)):
      k = A[i][0]+A[i][1]
      SecondColoumn.append(A[i][1])
      allRow.append(k)

A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]
compute_conditional_probabilites(A)
print(SecondColoumn)
print(allRow)
num=input("enter string to find probabilty")
ext=num[2:]
print("probabilty will be {}/{}".format(allRow.count(num),SecondColoumn.count(ext)))

['S1', 'S2', 'S3', 'S2', 'S3', 'S2', 'S1', 'S1', 'S3', 'S1']
['F1S1', 'F2S2', 'F3S3', 'F1S2', 'F2S3', 'F3S2', 'F2S1', 'F4S1', 'F4S3', 'F5S1']


enter string to find probabilty F1S1


probabilty will be 1/4


<h3> Q9: Operations on sentences </h3>

You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 unique values"
S2= "the second column S will contain only 3 unique values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [0]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

# you can free to change all these codes/structure
def string_features(S1, S2):
   a=0
   dict1={}
   dict2={}
   for word in S1.split():
      for words in S2.split():
         if word==words:
            a+=1

   for word in S1.split():
      dict1[word] = dict1.get(word, 0) + 1
      for words in S2.split():
         dict1[words] = dict1.get(words, 0) + 1
   b= ([word for word in dict1 if dict1[word] == 1])

   for word in S2.split():
      dict2[word] = dict2.get(word, 0) + 1
      for words in S1.split():
         dict2[words] = dict2.get(words, 0) + 1
   c=([word for word in dict2 if dict2[word] == 1])
   return a, b, c

# S1= "the first column F will contain only 5 uniques values"
# S2= "the second column S will contain only 3 uniques values"
S1=input("enter 1st String")
S2=input("enter 2nd String")
a,b,c = string_features(S1, S2)
print("Number of common words between S1, S2 :", a)
print("Words in S1 but not in S2 :",b)
print("Words in S2 but not in S1 :",c)

enter 1st String the first column F will contain only 5 uniques values
enter 2nd String the second column S will contain only 3 uniques values


Number of common words between S1, S2 : 7
Words in S1 but not in S2 : ['first', 'F', '5']
Words in S2 but not in S1 : ['second', 'S', '3']


<h3> Q10: Error Function</h3>

You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.44982
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [0]:

# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings
from math import log

# you can free to change all these codes/structure
def compute_log_loss(x,y):
   
   return -(1.0/len(x))*sum([x[i]*log(y[i],10) +(1.0-x[i])*log(1.0-y[i],10)for i in range(len(x))])
                           
# A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]

X=[]
Y=[]
n=int(input("enter the n:"))
for i in range(0,n):
   num1=int(input("enter x value"))
   num2=float(input("enter y value"))
   X.append(num1)
   Y.append(num2)
loss = compute_log_loss(X,Y)
print(loss)

enter the n: 8
enter x value 1
enter y value 0.4
enter x value 0
enter y value 0.5
enter x value 0
enter y value 0.9
enter x value 0
enter y value 0.3
enter x value 0
enter y value 0.6
enter x value 1
enter y value 0.1
enter x value 1
enter y value 0.9
enter x value 1
enter y value 0.8


0.42430993457031635
